
<?php require_once "header.php"; ?>


<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>Regolamento privacy Collection Sight</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>1. Informazioni generali</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito Collection Sight raccoglie, tratta e utilizza i tuoi dati personali in conformit&agrave; alle disposizioni italiane ed europee in materia di protezione dei dati. Ad eccezione di alcune informazioni obbligatorie che ci servono per poterti offrire i nostri servizi, puoi decidere tu stesso quali informazioni fornire e quali no.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Nel limite del possibile, nel nostro sito Web utilizziamo tecnologie di trasmissione sicure, ad esempio la crittografia TLS. Tuttavia, nonostante tutte le precauzioni, la trasmissione dei dati su Internet, soprattutto nell&rsquo;ambito della comunicazione tramite e-mail, pu&ograve; sempre presentare lacune in termini di sicurezza. Non &egrave; possibile proteggere ininterrottamente i dati dall&rsquo;accesso di terzi.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Utilizzando il sito Web&nbsp;</span><a href="http://www.collectionsight.com"><span style='font-size:16px;font-family:"Times New Roman",serif;color:#4472C4;text-decoration:none;'>www.collectionsight.com</span></a><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;e registrandoti come membro, acconsenti a Collection Sight di raccogliere, trattare ed utilizzare sui propri server i dati personali da te forniti, in qualit&agrave; di responsabile del trattamento. Ti informiamo che i dati da te trasmessi nell&apos;ambito dell&apos;utilizzo del sito Web vengono trattati e memorizzati con l&apos;ausilio di un sistema di elaborazione dati (EDP). I dati personali saranno ovviamente trattati in modo confidenziale.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Raccogliamo dati personali, ovvero informazioni singole relative a circostanze personali o concrete di una determinata persona fisica o determinabile, solo se necessitiamo questi dati ai fini della fornitura di servizi. Raccoglieremo esclusivamente i dati da te forniti. Il trattamento dei dati personali comprende la memorizzazione, la modifica, il trasferimento, il blocco e la cancellazione di tali dati. Tutti i dati personali verranno conservati solo per il periodo necessario alle rispettive finalit&agrave; menzionate o per il periodo di conservazione previsto dalla legge.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Le informazioni sull&apos;accesso (ad es. la data, l&rsquo;ora, la pagina visualizzata) possono gi&agrave; essere memorizzate sul server al momento della visita del nostro sito Web. Questi dati non rientrano nella categoria dei dati personali ma in quella dei dati anonimi, ad esempio il nome del provider Internet, il tipo di browser Internet, le pagine visitate all&rsquo;interno del sito Web. Analizziamo questi dati esclusivamente ai fini della statistica e del miglioramento dell&rsquo;offerta. Con la visita al nostro sito Web &egrave; anche possibile che dei dati vengano memorizzati sul tuo computer. Questi dati vengono chiamati &ldquo;cookie&rdquo; e facilitano l&rsquo;utilizzo del sito Web. Hai tuttavia la possibilit&agrave; di disattivare questa funzione all&rsquo;interno del tuo browser di rete. In questo caso potrebbero verificarsi delle limitazioni nell&rsquo;utilizzo delle nostre pagine.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati personali non vengono trasmessi a terzi. Sono esclusi da ci&ograve; solo i partner di servizio di Collection Sight, che ci servono per l&rsquo;esecuzione del rapporto contrattuale, ad esempio i fornitori di sistemi di pagamento per le donazioni (come PayPal) e il trasferimento di dati alle Autorit&agrave; nell&apos;ambito dell&apos;espletamento dei nostri obblighi legali. La portata della trasmissione dei dati &egrave; in ogni caso limitata al minimo.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Tuttavia, hai il diritto illimitato di revocare il tuo consenso in qualsiasi momento con effetto futuro. I dati di contatto per l&rsquo;esercizio del diritto di revoca presente <u>sul</u> nostro sito Web.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;utente ha il diritto di ricevere informazioni a riguardo, correggere, cancellare o bloccare i dati memorizzati in qualsiasi momento, nella misura in cui si tratti di dati personali ai sensi della RGPD. Per contattarci puoi utilizzare i dati di contatto disponibili nel nostro sito Web.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>2. Responsabile del trattamento</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Responsabile del trattamento ai sensi del Regolamento generale sulla protezione dei dati (RGPD) &egrave;:</span></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Collecton Sight</span></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>Indirizzo</span></strong></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Via Preazzi di Sotto 11/A<br>&nbsp;36013 &nbsp;Piovene Rocchette</span></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>Telefono</span></strong></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>+39 345 875 3375</span></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>E-Mail</span></strong></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></strong><a href="mailto:collectionsight@gmail.com"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>collectionsight@gmail.com</span></strong></a></p>
<p style='margin-top:0cm;margin-right:-11.25pt;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Dirigenti: Leonardo Carlassare, Thomas Porro, Nicol&ograve; Cervo</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>3. Nome e indirizzo del responsabile della protezione dei dati:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;incaricato della protezione dei dati del titolare del trattamento &egrave;:</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Leonardo Carlassare<br>&nbsp;Via Preazzi di Sotto, 11/A<br>&nbsp;36013 Piovene Rocchette</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>E-Mail:&nbsp;</span>leonardo.carlassare@studenti.unipd.it<span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>4. Informazioni generali sul trattamento dei dati</span></strong></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>In linea di principio, i dati personali vengono trattati solo se ci&ograve; &egrave; necessario per fornire un sito Web funzionante con tutti i contenuti e i servizi. Di regola i dati vengono trattati solo previo consenso dell&apos;interessato. In via eccezionale, i dati verranno trattati senza il consenso dell&apos;interessato qualora ci&ograve; non sia possibile per motivi legittimi e il trattamento dei dati sia consentito dalla legge.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;art. 6 cpv. 1 lett. a) del RGPD &egrave; la base giuridica per il trattamento dei dati personali, a condizione che la persona interessata abbia fornito il proprio consenso al trattamento dei dati personali.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;art. 6 cpv.1 lett. b) del RGPD &egrave; la base giuridica per il trattamento dei dati personali, nella misura in cui ci&ograve; &egrave; necessario per l&apos;esecuzione di un contratto di cui la persona interessata &egrave; parte. Ci&ograve; vale anche per le operazioni di trattamento necessarie all&apos;esecuzione di misure precontrattuali.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;art. 6 cpv.. 1 lett. c) del RGPD &egrave; la base giuridica per il trattamento dei dati personali, nella misura in cui il trattamento dei dati personali &egrave; necessario per adempiere a un obbligo legale cui &egrave; soggetta l&apos;azienda.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;art. 6 cpv.. 1 lett. f) del RGPD &egrave; la base giuridica per il trattamento dei dati personali, nella misura in cui ci&ograve; &egrave; necessario per la salvaguardia di un interesse legittimo dell&apos;azienda o di terzi e gli interessi, i diritti e le libert&agrave; fondamentali della persona interessata non prevalgono sul precedente interesse.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati personali dell&apos;interessato vengono cancellati o bloccati non appena decade la finalit&agrave; per la quale sono stati conservati. Inoltre, i dati possono essere memorizzati se ci&ograve; &egrave; previsto dalle normative nazionali o europee in materia. I dati vengono inoltre bloccati o cancellati in caso di scadenza del termine di conservazione previsto dalle suddette norme, a meno la stipula o l&apos;esecuzione di un contratto non richieda un&rsquo;ulteriore conservazione dei dati.</span></p>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>5. Utilizzo del sito Web</span></strong></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Ad ogni accesso al sito, il sistema raccoglie automaticamente dati e informazioni inviate dal sistema informatico del computer mediante il quale viene effettuato l&rsquo;accesso.</span></li>
    </ol>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Vengono raccolti i seguenti dati:</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;" type="1">
        <ol start="1" style="margin-bottom:0cm;" type="1">
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;indirizzo IP</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La data e l&rsquo;ora della richiesta</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La differenza di fuso orario rispetto all&apos;ora di Greenwich (GMT)</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il contenuto della pagina Web</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Lo stato dell&rsquo;accesso (stato HHTP)</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La quantit&agrave; di dati trasferiti</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il browser di rete</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La lingua e la versione del browser</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sistema operativo</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito internet dal quale viene effettuato l&rsquo;accesso al sito internet</span></li>
        </ol>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati vengono memorizzati nei file di registro del sistema. Questi dati non vengono memorizzati insieme ad altri dati personali dell&apos;utente.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="2" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La base giuridica &egrave; l&apos;art. 6 cpv. 1 lett. f) del RGPD.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La raccolta e la memorizzazione temporanea dell&apos;indirizzo IP sono necessarie per consentire la visualizzazione del sito Web sul dispositivo. A questo scopo, il vostro indirizzo IP deve essere memorizzato per tutta la durata della vostra visita al sito Web. Questi dati non vengono analizzati a scopi di marketing.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati vengono cancellati al termine della sessione. Se questi dati vengono memorizzati in file di registro, vengono cancellati al pi&ugrave; tardi dopo sette giorni. &Egrave; possibile conservare i dati oltre questa scadenza. In questo caso gli indirizzi IP degli utenti vengono cancellati o anonimizzati, in modo che non possano pi&ugrave; messi in relazione al client .che ha visitato il sito.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La raccolta dei dati e la memorizzazione di tali dati in file di registro &egrave; assolutamente necessaria per mettere a disposizione il sito Web. Di conseguenza, non &egrave; possibile fare opposizione a tale raccolta.</span></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:32px;font-family:"Segoe UI",sans-serif;color:#012169;'>6. Funzioni di registrazione</span></strong></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito offre agli utenti la possibilit&agrave; di registrarsi mediante trasmissione di dati personali. I dati vengono inseriti in un modulo di immissione, trasmessi e memorizzati. Non vengono trasmessi dati a terzi. Durante il processo di registrazione vengono raccolti i seguenti dati:</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;" type="1">
        <ol start="1" style="margin-bottom:0cm;" type="1">
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il nome (nome, cognome)</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;indirizzo di domicilio (via, n. civico, CAP, paese)</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;indirizzo e-mail</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La data e l&rsquo;ora della registrazione</span></li>
        </ol>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Durante la registrazione, l&apos;utente acconsente al trattamento di questi dati secondo la dichiarazione sulla protezione dei dati.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="2" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La base giuridica &egrave; l&apos;art. 6 cpv. 1 lett. a) del RGPD, se l&apos;utente ha dato il suo consenso. Se la registrazione serve ai fini dell&rsquo;esecuzione di un contratto di cui l&apos;utente &egrave; parte contrattuale o della messa in atto di misure precontrattuali, l&apos;art. 6 cpv. 1 lett. b) del RGPD funge da base giuridica supplementare per il trattamento dei dati. Nella misura in cui siamo obbligati a trattare i dati da utenti commerciali e venditori privati, la base giuridica &egrave; l&apos;articolo 6, comma 1 c).</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;utente deve registrarsi per creare un account cliente. La registrazione &egrave; necessaria ai fini dell&rsquo;identificazione dell&apos;utente e dell&rsquo;adempimento del contratto d&apos;uso del servizio. I dati forniti da utenti commerciali o venditori privati vengono utilizzati per l&apos;adempimento dei nostri obblighi legali nei confronti delle Autorit&agrave; Fiscali.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati saranno cancellati non appena non saranno pi&ugrave; necessari per il raggiungimento della finalit&agrave; per il quale sono stati raccolti. Anche dopo la stipula del contratto pu&ograve; essere necessario conservare i dati personali del partner contrattuale ai fini dell&rsquo;adempimento di obblighi contrattuali o di legge.</span></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>7. Contatto tramite e-mail o modulo di contatto</span></strong></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito Web utilizza moduli di contatto che possono essere utilizzati per contattarci elettronicamente. All&rsquo;utilizzo, i dati immessi nel modulo verranno trasmessi al sito Web dove verranno memorizzati. Questi dati comprendono:</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;" type="1">
        <ol start="1" style="margin-bottom:0cm;" type="1">
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;indirizzo e-mail</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il contenuto del messaggio di presa di contatto</span></li>
        </ol>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Inoltre, alla presa di contatto vengono raccolti i seguenti dati:</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;" type="1">
        <ol start="3" style="margin-bottom:0cm;" type="1">
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;indirizzo IP del computer che visita il sito</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La data e l&rsquo;ora del contatto</span></li>
        </ol>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>In questo contesto, i dati non verranno trasmessi a terzi. I dati vengono utilizzati esclusivamente per l&apos;elaborazione della conversazione.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="2" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se l&rsquo;utente ha dato il suo consenso, la base giuridica per il trattamento dei dati &egrave; l&apos;art. 6 cpv. 1 lett. a) del RGPD.</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La base giuridica per il trattamento dei dati trasmessi nell&apos;ambito dell&apos;invio di un&apos;e-mail &egrave; l&apos;art. 6 cpv. 1 lett. f) del RGPD.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se la presa di contatto tramite e-mail avviene ai fini della stipula o dell&rsquo;adempimento di un contratto, la base giuridica supplementare per l&apos;elaborazione &egrave; l&apos;art. 6 cpv. 1 lett. b) del RGPD.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="3" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati personali contenuti nel modulo di contatto vengono trattati esclusivamente ai fini dell&rsquo;elaborazione della richiesta. In caso di presa di contatto tramite e-mail, ci&ograve; costituisce anche il necessario interesse legittimo al trattamento dei dati.</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Gli altri dati personali trattati durante il processo di invio servono a prevenire abusi del modulo di contatto e a garantire la sicurezza dei sistemi informatici.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="4" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati saranno cancellati non appena non saranno pi&ugrave; necessari per il raggiungimento dello scopo per il quale sono stati raccolti. I dati personali contenuti nel modulo di immissione del modulo di contatto e quelli inviati via e-mail vengono cancellati quando la conversazione con l&apos;interessato &egrave; terminata. La conversazione &ecirc; considerata terminata quando le circostanze inducono ad evincere che i fatti in questione sono stati chiariti definitivamente. I dati personali aggiuntivi raccolti durante il l&rsquo;invio vengono cancellati al pi&ugrave; tardi dopo sette giorni.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;interessato pu&ograve; revocare in qualsiasi momento il proprio consenso al trattamento dei dati personali. In caso di contatto tramite e-mail, &egrave; possibile opporsi in qualsiasi momento alla memorizzazione dei dati personali. In tal caso non &egrave; tuttavia possibile proseguire la conversazione. Tutti i dati personali memorizzati nel corso del contatto in questo caso verranno cancellati.</span></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>11. Utilizzo di cookie</span></strong></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito web utilizza i cookie. I cookie sono file di testo che vengono memorizzati nel browser Internet o dal browser Internet nel sistema informatico dell&apos;utente. Questi cookie contengono una caratteristica sequenza di caratteri che consente di identificare in modo univoco il browser alla prossima visita del sito Web. I cookie non possono trasmettere virus al dispositivo n&eacute; eseguire autonomamente dei programmi.</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I cookie vengono utilizzati per semplificare l&rsquo;utilizzo di un sito web. Alcuni elementi del sito Web richiedono l&rsquo;identificazione del browser che visita il sito anche dopo un cambio di pagina.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I cookie transitori vengono eliminati automaticamente alla chiusura della sessione. Dei cookie transitori fanno parte i cookie di sessione, che memorizzano il cosiddetto ID di sessione, che pu&ograve; essere messo in relazione alla sessione condivisa in base alle varie richieste provenienti dal browser Web. In questo modo &egrave; possibile riconoscere il dispositivo mobile durante una nuova sessione.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I cookie persistenti vengono eliminati automaticamente dopo un periodo di archiviazione specificato, che pu&ograve; variare a seconda del cookie. Le rispettive impostazioni possono essere cancellate in qualsiasi momento nelle impostazioni del browser di rete.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Nei cookie vengono memorizzati i seguenti dati:</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;" type="1">
        <ol start="1" style="margin-bottom:0cm;" type="1">
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Le informazioni di accesso</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Le impostazioni della lingua</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I termini di ricerca inseriti</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il numero di accessi al sito Web</span></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;utilizzo di singole funzioni del sito Web</span></li>
        </ol>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="2" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La base giuridica &egrave; l&apos;art. 6 cpv. 1 lett. f) del RGPD.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Lo scopo dell&rsquo;utilizzo di cookie tecnicamente necessari &egrave; quello di semplificare l&apos;utilizzo dei siti Web da parte degli utenti. Alcune funzioni del sito Web non possono essere offerte senza l&rsquo;impiego di cookie. Per questo &egrave; necessario che il browser venga riconosciuto anche dopo un cambio di pagina.</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I dati dell&apos;utente raccolti tramite i cookie tecnicamente necessari non vengono utilizzati per creare profili utente.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="4" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>I cookie vengono memorizzati sul computer dell&apos;utente e trasmessi al nostro sito. Pertanto lei in qualit&agrave; di utente, ha anche il pieno controllo sull&apos;utilizzo dei cookie. &Egrave; possibile disattivare o limitare l&rsquo;utilizzo dei cookie modificando le impostazioni del browser Internet. I cookie gi&agrave; salvati possono essere cancellati in qualsiasi momento, anche mediante cancellazione automatica. Se i cookie vengono disattivati per il nostro sito Web, potrebbe non essere pi&ugrave; possibile utilizzare tutte le funzioni del sito Web.</span></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>12. Google Analytics</span></strong></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="1" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito Web utilizza &quot;Google Analytics&quot;, un servizio di analisi di rete di Google Inc, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA (in seguito &quot;Google&quot;). Google utilizza dei &quot;cookie&quot;, ovvero piccoli file di testo che vengono memorizzati sul dispositivo e che consentono di analizzare l&apos;utilizzo di Internet. Le informazioni generate dai cookie sull&apos;utilizzo di questo sito Web vengono di solito trasferite a un server di Google negli Stati Uniti, dove vengono conservate. Se l&apos;indirizzo IP da trasmettere tramite il cookie viene attivato con l&apos;estensione &quot;_anonymizeIp()&quot; sul sito Web (in seguito &ldquo;anonimizzazione dell&rsquo;IP&rdquo;), Google abbrevier&agrave; il vostro indirizzo IP negli Stati membri dell&apos;Unione europea o in altri Stati parti dell&apos;accordo sullo Spazio economico europeo, prima di trasmetterlo. Solo in casi eccezionali l&apos;indirizzo IP completo viene trasmesso a un server di Google negli USA, dove verr&agrave; abbreviato. Google utilizzer&agrave; queste informazioni allo scopo di tracciare ed esaminare l&apos;utilizzo del sito Web per conto del titolare del trattamento, compilare report sull&apos;utilizzo e fornire ulteriori servizi legati all&apos;utilizzo del sito web e di Internet. Dai dati elaborati possono essere creare profili utente tramite l&rsquo;uso di pseudonimi. L&apos;indirizzo IP trasmesso durante l&apos;utilizzo di Google Analytics non viene messo in relazione ad altri dati di Google.</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito Web utilizza Google Analytics solo con l&apos;anonimizzazione dell&apos;IP precedentemente descritta. Significa che Google elaborer&agrave; il vostro indirizzo IP solo in forma abbreviata. Questo indirizzo IP non permette quindi di risalire alla persona.</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="2" style="margin-bottom:0cm;margin-top:0cm;" type="1">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>La base giuridica del trattamento &egrave; l&apos;interesse legittimo all&apos;analisi, all&apos;ottimizzazione e allo sfruttamento economico del sito Web ai sensi dell&apos;art. 6 cpv. 1 lett. f) del RGPD.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il sito Web utilizza Google Analytics allo scopo di analizzare l&apos;utilizzo del sito Web e di migliorare continuamente le singole funzioni e offerte, nonch&eacute; l&apos;esperienza utente. La valutazione statistica del comportamento dell&apos;utente pu&ograve; migliorare l&apos;offerta e renderla pi&ugrave; interessante per lo stesso. Anche in questo consiste il legittimo interesse al trattamento dei dati da parte di Google.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&Egrave; possibile impedire la memorizzazione dei cookie generati da Google Analytics mediante impostazione adeguata del browser di rete. Va precisato che in tal caso potrebbe non essere possibile utilizzare tutte le funzionalit&agrave; del sito Web. Se si desidera impedire la raccolta dei dati generati dal cookie e relativi al comportamento dell&apos;utente (compreso il vostro indirizzo IP) e l&apos;elaborazione di questi dati da parte di Google, &egrave; possibile scaricare e installare il plug-in per il browser di rete disponibile al seguente link:&nbsp;</span><a href="http://tools.google.com/dlpage/gaoptout" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:     none;'>http://tools.google.com/dlpage/gaoptout</span></strong></a><span style='font-size:16px;font-family:"Times New Roman",serif;'>.</span></li>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Al fine di obbligare Google a elaborare i dati trasmessi esclusivamente in conformit&agrave; alle istruzioni e alle disposizioni vigenti in materia di protezione dei dati, il titolare del trattamento ha stipulato con Google un contratto per il trattamento dei dati.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Per i casi eccezionali in cui i dati personali vengono trasferiti negli Stati Uniti, Google ha aderito allo Scudo UE-USA per la privacy stipulato tra l&apos;Unione Europea e gli Stati Uniti e si &egrave; certificata. Google si impegna a rispettare le norme e le disposizioni del diritto europeo in materia di protezione dei dati. Ulteriori informazioni sono disponibili al seguente indirizzo:&nbsp;</span><a href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</span></strong></a></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Informazioni del fornitore terzo: Google Dublin, Google Ireland Ltd., Gordon House, Barrow Street, Dublino 4, Irlanda, Fax: +353 (1) 436 1001. Ulteriori informazioni sull&apos;utilizzo dei dati da parte di Google, sulle possibilit&agrave; di impostazione e di opposizione e sulla protezione dei dati sono disponibili sulle seguenti pagine Web di Google:</span></p>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <ol start="4" style="margin-bottom:0cm;" type="1">
        <ol start="1" style="margin-bottom:0cm;" type="1">
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Condizioni di utilizzo:<br>&nbsp;</span><a href="http://www.google.com/analytics/terms/" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:      none;'>http://www.google.com/analytics/terms/</span></strong></a></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Panoramica sulla protezione dei dati:<br>&nbsp;</span><a href="http://www.google.com/intl/de/analytics/learn/privacy.html" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>http://www.google.com/intl/de/analytics/learn/privacy.html</span></strong></a></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Informativa sulla privacy:<br>&nbsp;</span><a href="https://www.google.com/intl/de/policies/privacy/" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>https://www.google.com/intl/de/policies/privacy/</span></strong></a></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Utilizzo dei dati da parte di Google quando si utilizzano i siti Web o le app dei nostri partner:<br>&nbsp;</span><a href="https://www.google.com/intl/de/policies/privacy/partners/" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>https://www.google.com/intl/de/policies/privacy/partners/</span></strong></a></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Utilizzo dei dati per finalit&agrave; promozionali:<br>&nbsp;</span><a href="https://www.google.com/policies/technologies/ads/" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>https://www.google.com/policies/technologies/ads/</span></strong></a></li>
            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:-18.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Impostazioni promozionali personalizzate tramite Google:<br>&nbsp;</span><a href="http://www.google.de/settings/ads" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:      none;'>http://www.google.de/settings/ads</span></strong></a></li>
        </ol>
    </ol>
</div>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;border:none;border-left:solid #DFC463 1.5pt;padding:0cm 0cm 0cm 6.0pt;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>In alternativa all&rsquo;Add On del browser o all&apos;interno di browser su dispositivi mobili, inserire&nbsp;</span><a href="https://www.cardmarket.com/it/PostGetAction/User_DisableAnalytics?cookieName=ga_optOut" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>opt out</span></strong></a><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;per impedire la raccolta da parte di Google Analytics all&apos;interno di questo sito Web in futuro. Un cookie di opt-out viene memorizzato sul tuo dispositivo. Eliminando i tuoi cookie, dovrai nuovamente fare clic su questo link.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;border:none;padding:0cm;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Per i visitatori che accedano al nostro sito Web dalla Repubblica popolare cinese (RPC), &egrave; possibile che invece di Google Analytics utilizziamo per lo stesso scopo e con le stesse restrizioni i servizi di Site Monitor del provider Miaozhen Ltd, Pechino, RPC con server nella RPC. Per disattivare i servizi di monitoraggio del sito, visitare&nbsp;</span><a href="http://i.miaozhen.com.cookie_opt.html/" target="_blank"><strong><span style='font-size:16px;font-family:"Times New Roman",serif;color:#0240CA;text-decoration:none;'>http://i.miaozhen.com.cookie_opt.html</span></strong></a></p>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>13. Trasmissione crittografata dei dati</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>All&rsquo;iscrizione (&quot;login&quot;) o alla presa di contatto, tutti i dati vengono trasmessi tramite una connessione crittografata con tecnologia TLS. Il certificato richiesto, installato sui server, &egrave; stato emesso da un&apos;organizzazione indipendente.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Una connessione crittografata pu&ograve; essere riconosciuta dal fatto che la riga dell&apos;indirizzo del browser cambia da http:// a https://.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Non appena viene stabilita la connessione TLS crittografata, i dati da te inseriti e trasmessi al negozio, non possono pi&ugrave; essere letti da terzi.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:31px;font-family:"Times New Roman",serif;color:#012169;'>14. Diritti della persona interessata</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se i dati personali vengono trattati da , gli utenti sono &quot;interessati&quot; ai sensi del RGPD e hanno i seguenti diritti nei confronti del titolare del trattamento:</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="1" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto di informazione</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;interessato pu&ograve; chiedere al titolare del trattamento la conferma dell&apos;esistenza o meno di un trattamento di dati personali.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se tale trattamento ha avuto luogo, al titolare del trattamento pu&ograve; essere richiesto di fornire le seguenti informazioni:</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Times New Roman",serif;'>le finalit&agrave; per le quali i dati personali v trattati;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>le categorie di dati personali trattati;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>i destinatari o le categorie di destinatari ai quali i dati personali sono stati trasmessi o si trovano tuttora in fase di trasmissione;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>la durata prevista della conservazione dei dati personali o, qualora non sia possibile fornire informazioni specifiche, i criteri per la determinazione del periodo di conservazione;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>l&apos;esistenza di un diritto di rettifica o di cancellazione dei dati personali, di un diritto di limitazione del trattamento da parte del responsabile del trattamento o di un diritto di opposizione a tale trattamento;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>l&apos;esistenza di un diritto di reclamo presso un&apos;autorit&agrave; di controllo;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>qualsiasi informazione disponibile sull&apos;origine dei dati se i dati personali non sono raccolti presso l&apos;interessato;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>l&apos;esistenza di un processo decisionale automatizzato, compresa la definizione di profili ai sensi dell&apos;articolo 22, capoversi 1 e 4, del RGPD e - almeno in questi casi - di informazioni significative sulla logica in questione, nonch&eacute; sulla portata e sugli effetti previsti di tale trattamento per la persona interessata.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Sussiste il diritto di informarsi se i dati personali vengono trasmessi a un paese terzo o a un&apos;organizzazione internazionale. In tale contesto l&rsquo;utente pu&ograve; richiedere di essere informato in merito alle garanzie adeguate ai sensi dell&apos;art. 46 del RGPD in relazione alla trasmissione.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="2" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto di rettifica</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se i dati personali trattati sono errati o incompleti, l&rsquo;utente ha il diritto di chiedere al titolare del trattamento la rettifica e/o il completamento Il titolare del trattamento deve procedere senza indugio alla rettifica.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="3" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto di limitazione di trattamento</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il trattamento dei dati personali pu&ograve; essere richiesto alle condizioni seguenti:</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Times New Roman",serif;'>qualora venisse contestata l&apos;accuratezza dei dati personali per un periodo di tempo tale da consentire alla persona responsabile di verificarla;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>se il trattamento &egrave; illecito e la cancellazione dei dati personali &egrave; stata rifiutata e in cambio &egrave; stata richiesta la limitazione dell&apos;uso dei dati personali;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>il responsabile del trattamento non ha pi&ugrave; bisogno dei dati personali ai fini del trattamento, ma questi dati sono necessari per far valere, esercitare o difendere un diritto in sede giudiziaria, oppure</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>in caso di opposizione al trattamento ai sensi dell&apos;art. 21 cpv. 1 del RGPD e nel qual caso non sia stato ancora accertato se le ragioni legittime del titolare del trattamento prevalgano su quelle della persona interessata.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Qualora il trattamento dei dati personali sia stato limitato, tali dati possono essere trattati, oltre che memorizzati, solo con il consenso della persona interessata o al fine di far valere, esercitare o difendere diritti o tutelare diritti di un&apos;altra persona fisica o giuridica o per un interesse pubblico rilevante dell&apos;Unione o di uno Stato membro.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se la limitazione del trattamento &egrave; stata limitata conformemente alle condizioni di cui sopra, il responsabile del trattamento ne informa l&apos;interessato prima che la limitazione sia revocata.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="4" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto alla cancellazione</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Obbligo di cancellazione</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il titolare del trattamento ha il diritto di chiedere che i dati personali vengano cancellati immediatamente e il titolare del trattamento &egrave; tenuto a cancellarli immediatamente se si verifica una delle seguenti circostanze:</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Times New Roman",serif;'>i dati personali non sono pi&ugrave; necessari per le finalit&agrave; per le quali sono stati raccolti o in altro modo trattati.</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>Il consenso su cui si basa il trattamento ai sensi dell&apos;art. 6 cpv. 1 lett. a) o dell&apos;art. 9 cpv. 2 lett. a) del RGPD &egrave; stato revocato e non sussiste alcun altro fondamento giuridico per il trattamento.</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>Il trattamento ai sensi dell&apos;art. 21 cpv. 1 del RGPD &egrave; oggetto di opposizione e non sussiste alcun motivo imperativo e legittimo per il trattamento, oppure &egrave; oggetto di opposizione ai sensi dell&apos;art. 21 cpv. 2 del RGPD.</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>I dati personali sono stati trattati illecitamente.</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>La cancellazione di dati personali &egrave; necessaria per adempiere a un obbligo legale previsto dal diritto dell&apos;Unione o dal diritto degli Stati membri cui &egrave; soggetto il titolare del trattamento.</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>I dati personali sono stati raccolti in relazione ai servizi della societ&agrave; dell&apos;informazione offerti ai sensi dell&apos;art. 8 cpv. 1 del RGPD.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Informazioni a terzi</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se il titolare del trattamento ha reso pubblici i dati personali ed &egrave; obbligato cancellarli ai sensi dell&apos;art. 17 cpv. 1 del RGPD, deve adottare misure adeguate, anche di natura tecnica, tenendo conto della tecnologia disponibile e dei costi di attuazione, per informare i responsabili del trattamento che gli interessati hanno richiesto di cancellare tutti i link a tali dati personali o ne hanno richiesto una copia o replica.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Deroghe</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il diritto di cancellazione non sussiste nella misura in cui il trattamento &egrave; necessario</span></p>
<ol style="list-style-type: undefined;">
    <li><span style='font-family:"Times New Roman",serif;'>ad esercitare la libert&agrave; di espressione e di informazione;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>per l&apos;esecuzione di obblighi giuridici derivanti dal diritto dell&apos;Unione o degli Stati membri cui &egrave; soggetto il titolare del trattamento o per ottemperare a compito di interesse pubblico o dell&apos;esercizio di pubblici poteri conferita a quest&apos;ultimo;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>per motivi di interesse pubblico nel settore della sanit&agrave; pubblica ai sensi dell&apos;art. 9 cpv. 2 lett. h) e i) e dell&apos;art. 9 cpv. 3 del RGPD;</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>per scopi di archiviazione di interesse pubblico, per scopi di ricerca scientifica o storica o per scopi statistici ai sensi dell&apos;art. 89 cpv. 1 del RGPD, nella misura in cui la legge di cui alla lett. a) possa rendere impossibile o pregiudicare gravemente il raggiungimento degli scopi del trattamento, oppure</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>per far valere, esercitare o difendere un diritto in sede giudiziaria.</span></li>
</ol>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="5" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto all&apos;informazione</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se nei confronti del titolare del trattamento &egrave; stato fatto valere il diritto di rettifica, cancellazione o limitazione del trattamento, questi &egrave; tenuto ad informare tutti i destinatari ai quali sono stati comunicati i dati personali di tale rettifica o cancellazione o limitazione, a meno che ci&ograve; non risulti impossibile o implichi uno sforzo sproporzionato.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&rsquo;utente ha il diritto di essere informato dal titolare del trattamento in merito a tali destinatari.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="6" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto alla trasferibilit&agrave; dei dati</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Esiste il diritto di ricevere i dati personali forniti al responsabile del trattamento in un formato strutturato, comune e leggibile elettronicamente. Inoltre, i dati possono essere comunicati a un altro responsabile del trattamento senza interferenze che il responsabile al quale sono stati forniti i dati personali lo impedisca, a condizione che</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Times New Roman",serif;'>il trattamento si basi sul consenso ai sensi dell&apos;art. 6 cpv. 1 lett. a) del RGPD o dell&apos;art. 9 cpv. 2 lett. a) del RGPD o su un contratto ai sensi dell&apos;art. 6 cpv.. 1 lett. b) del RGPD e</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>il trattamento avviene mediante procedure automatizzate.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Nell&apos;esercizio di tale diritto, sussiste inoltre anche il diritto fare in modo che i dati personali vengano trasferiti direttamente da un responsabile del trattamento a un altro, se questo &egrave; tecnicamente fattibile. Questo non deve pregiudicare le libert&agrave; e i diritti di altre persone.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il diritto alla trasferibilit&agrave; dei dati non si applica al trattamento dei dati personali necessari all&apos;esercizio di una funzione di interesse pubblico o dell&apos;autorit&agrave; di controllo conferita al titolare del trattamento.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="7" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto di opposizione</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;interessato ha il diritto di opporsi in qualsiasi momento al trattamento dei dati personali ai sensi dell&apos;articolo 6, capoverso 1, lettere e) o f), del RGPD per ragioni legate alla sua situazione specifica; ci&ograve; vale anche per la profilazione basata su tali disposizioni.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Il titolare del trattamento non tratta pi&ugrave; i dati personali a meno che non sia in grado di dimostrare l&rsquo;esistenza di motivi impellenti per la protezione del trattamento prevalenti sugli interessi, sui diritti e sulle libert&agrave; dell&apos;interessato o che i dati vengono trattati allo scopo di far valere, esercitare o difendere un diritto in sede giudiziaria.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Se i dati personali vengono trattati per finalit&agrave; di marketing diretto, esiste il diritto di opporsi in qualsiasi momento al trattamento dei dati personali ai fini di questo tipo di pubblicit&agrave;; ci&ograve; vale anche per la profilazione se &egrave; associata a tale marketing diretto.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>In caso di opposizione al trattamento per finalit&agrave; di marketing diretto, i dati personali non verranno pi&ugrave; trattati per tali finalit&agrave;.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Nell&rsquo;ambito dell&rsquo;utilizzo di servizi della societ&agrave; di informazione il diritto di opposizione pu&ograve; essere esercitato mediante procedure automatizzate con tecniche specifiche. In deroga alla direttiva 2002/58/CE</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="8" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto di revoca del consenso al trattamento dei dati</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Sussiste il diritto di revocare in qualsiasi momento il consenso al trattamento dei dati. La revoca del consenso non pregiudica la legittimit&agrave; del trattamento effettuato sulla base dello stesso fino al momento della revoca.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0cm;list-style-type: lower-roman;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Processo decisionale automatizzato in casi singoli inclusa la profilazione</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Sussiste diritto di non assoggettarsi una decisione basata esclusivamente su un trattamento automatizzato, compresa la profilazione, che comporti effetti giuridici o effetti analoghi per la persona interessata o abbia un effetto negativo considerevole su di essa . Questo diritto non sussiste se la decisione</span></p>
<ol class="decimal_type" style="list-style-type: decimal;">
    <li><span style='font-family:"Times New Roman",serif;'>&egrave; necessaria per la conclusione o l&apos;esecuzione di un contratto tra l&apos;interessato e il titolare del trattamento</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>&egrave; consentita dalle disposizioni legali dell&apos;Unione o degli Stati membri alle quali &egrave; soggetta la persona responsabile e tale diritto contiene misure idonee a salvaguardare i diritti, le libert&agrave; e gli interessi legittimi di quest&apos;ultima, oppure</span></li>
    <li><span style='font-family:"Times New Roman",serif;'>viene presa con il consenso esplicito della persona interessata.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Queste decisioni non possono tuttavia basarsi su categorie particolari di dati personali ai sensi dell&apos;art. 9 cpv. 1 del RGPD, a meno che non venga applicato l&apos;art. 9 cpv. 2 lett. a) o g) e non siano state adottate misure adeguate per proteggere i vostri diritti, le vostre libert&agrave; e i vostri interessi legittimi.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Nei casi di cui ai paragrafi (1) e (3), il titolare del trattamento adotta misure adeguate a salvaguardare i diritti, le libert&agrave; e gli interessi legittimi dell&apos;interessato, compreso almeno il diritto di ottenere l&apos;intervento di una persona per conto del titolare del trattamento, di spiegare il proprio parere e di impugnare la decisione.</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol start="10" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:26px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Times New Roman",serif;'>Diritto di reclamo presso un&rsquo;autorit&agrave; di controllo</span></strong></li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Salvo altri ricorsi amministrativi o giudiziari, il diritto di reclamo presso un&apos;autorit&agrave; di controllo, in particolare nello Stato membro di residenza della persona interessata, nel luogo di lavoro o nel luogo in cui &egrave; avvenuta la presunta infrazione, sussiste qualora si ritenga che il trattamento dei dati personali sia contrario al RGPD.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>L&apos;autorit&agrave; di controllo presso la quale &egrave; stato presentato il reclamo informa la persona che inoltra reclamo sullo stato e sui i risultati del reclamo e la informa anche sulla possibilit&agrave; di un ricorso giurisdizionale ai sensi dell&apos;articolo 78 del RGPD.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>



<? require "footer.php"; ?>